### ISSUE TITLE
About the model release

### ISSUE THREAD

**Issue by Frankie123421** [luka-group/prix-lm#1]
I notice that the "model_name_or_path" is "wzhouad/prix-lm", can you please provide the model?

**Comment by wzhouad** [comment]
The model is released at the HuggingFace Hub https://huggingface.co/wzhouad/prix-lm

**Comment by Frankie123421** [comment]
> The model is released at the HuggingFace Hub https://huggingface.co/wzhouad/prix-lm

Thanks for your reply.
